INSERT INTO questions (question, guidance)
VALUES
('Tell me about yourself.',
'This is often the first of many interview questions, designed to ‘warm up’ the candidate. Many candidates choose to respond with an overview of their work and employment history. Whilst this is helpful – especially if a manager hasn’t read your CV in detail, it’s important you offer new information, such as what are your hobbies outside of work. It’s also easy to fall into the trap of waffling. Other candidates prefer to focus on a key aspect of their career, building a story around it with performance highlights. It’s important to ensure your answer is aligned with the job description and advertisement, to demonstrate how you can add value to the company and role at hand.'),
('What attracted you to our company?',
'This is your opportunity to demonstrate that you’ve done your research. Prior to the interview, read up on everything you can about the company from their own website, social media channels and other news articles and forums. Identify what stands out about the company’s mission and values, and how that resonates with your own desired career path and personal values.'),
('Tell me about your strengths.',
'This should be the easiest question to prepare for. Identify two or three of your best attributes and give concrete examples of those strengths, articulating how they led to the professional success you achieved. Be sure to close the loop and articulate how they are relevant to the job you’re interviewing for.'),
('Where do you see yourself in five years?',
'Your employer wants to see how driven and goal-oriented you are. They also want to check that your expectations are realistic. In your answer, demonstrate your awareness of industry trends and ability to be flexible.'),
('What are your weaknesses?',
'Take the time to craft an answer that isn’t a cliché. Nothing makes a hiring manager cringe more than the answer: “I’m a perfectionist.” This is your opportunity to demonstrate your own self-awareness and desire for personal development. Try to identify something that isn’t critical to the role, and frame your answer in the positive.'),
('Can you tell me about a time where you encountered a business challenge? How did you overcome it?',
'Behavioural question alert! This is your opportunity to use the CAR method: Context, Action, and Result. Choose an example that demonstrates where you have solved a business challenge using a skill that the employer is looking for. Provide the background, describe what action you took and the professional result you achieved.'),
('Do you have any questions for me?',
'It’s important to come with a list of pre-prepared interview questions . Some of these might already be answered during the course of the interview, so check these off as you go, to avoid asking the same question twice.'),
('What are the most important things you are looking for in your next role?',
'Start with your skills. Identify a skill that you exceed in and talk about how you are looking for a role that will utilise and further develop that skill. You should also explain your motivations and how this role can help you achieve your long-term goals. Always ensure that your answer is relevant to the company and the role in question.'),
('Why are you leaving your current job?',
'It’s critical to frame your answer in the positive. Never say anything negative about your current employer, no matter how strongly your feelings for leaving are. Instead, focus on the specific, positive things that a career change to the new role will bring, for example, professional development opportunities or the excitement of a new challenge.'),
('What are your salary expectations?',
'Do your research beforehand. Our Salary Guide can give you the latest salary trends and benchmarks. If you come prepared with reasonable salary expectations, you and your employer will know straight away if you are going to feel sufficiently compensated in the role.');